;/*FB_PKG_DELIM*/

__d("CometSSRHydrationMarkerUtils",["cr:1106516"],(function(a,b,c,d,e,f,g){"use strict";a=b("cr:1106516")==null?void 0:b("cr:1106516").addMarkersToChildren;c=b("cr:1106516")==null?void 0:b("cr:1106516").addMarkersToFallback;d=b("cr:1106516")==null?void 0:b("cr:1106516").injectStyles;g.addMarkersToChildren=a;g.addMarkersToFallback=c;g.injectStyles=d}),98);
__d("CometSuspenseHUD.react",["cr:1064332","cr:4874"],(function(a,b,c,d,e,f,g){"use strict";a=b("cr:1064332")!=null?b("cr:1064332"):b("cr:4874");g["default"]=a}),98);
__d("useCometPlaceholderImpl",["CometSSRHydrationMarkerUtils","CometSuspenseHUD.react","ExecutionEnvironment","cr:22912","cr:5128","hero-tracing-placeholder","react","useStable"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||(i=d("react")),k=i,l=k.useCallback,m=k.useRef,n=b("cr:22912")||b("cr:5128");function e(b){var e=b.children,f=b.fallback,g=b.name,i=b.unstable_avoidThisFallback,k=b.unstable_onSuspense,o=c("useStable")(function(){return c("CometSuspenseHUD.react")&&(h||(h=c("ExecutionEnvironment"))).canUseDOM?a.document.createElement("div"):null}),p=m(null),q=c("useStable")(d("hero-tracing-placeholder").HeroPlaceholderUtils.getSimpleUUID);b=e;e=f;d("CometSSRHydrationMarkerUtils").addMarkersToChildren!=null&&d("CometSSRHydrationMarkerUtils").addMarkersToFallback!=null&&(b=d("CometSSRHydrationMarkerUtils").addMarkersToChildren(b),e=d("CometSSRHydrationMarkerUtils").addMarkersToFallback(e));f=l(function(a,b){o!=null&&(o.textContent=a),p.current=a,n==null||n.trackSuspendedComponent==null||n.trackSuspendedComponent(a,q,b),k&&k(a)},[o,k]);var r=null;o!=null&&c("CometSuspenseHUD.react")!=null&&(r=j.jsx(c("CometSuspenseHUD.react"),{desc:o}));e=j.jsxs(j.Fragment,{children:[e,r]});r=b;return j.jsx(d("hero-tracing-placeholder").HeroPlaceholder,{fallback:e,name:g,placeholderUUID:q,unstable_avoidThisFallback:i,unstable_onSuspense:f,children:r})}e.displayName=e.name+" [from "+f.id+"]";g["default"]=e}),98);
__d("CometPlaceholder.react",["react","useCometPlaceholderImpl"],(function(a,b,c,d,e,f,g){"use strict";var h;h||d("react");function a(a){return c("useCometPlaceholderImpl")(a)}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("RDFDRequireDeferredReference",["RequireDeferredReference"],(function(a,b,c,d,e,f,g){"use strict";a=function(a){function b(){return a.apply(this,arguments)||this}babelHelpers.inheritsLoose(b,a);return b}(c("RequireDeferredReference"));g["default"]=a}),98);
__d("deferredLoadComponentBase",["ExecutionEnvironment","Promise","PromiseAnnotate","react","suspendOrThrowIfUsedInSSR"],(function(a,b,c,d,e,f,g){var h=["ref"],i=["loadImmediately"],j,k,l,m,n,o=n||c("react"),p={},q={},r=new Map();function s(a,b){r.set(a,b)}function t(a){return r.get(a)}function a(a,e){var g=t(a);if(g)return g;var n,r=a.getModuleId();function u(){var c=q[r];c||(c=q[r]=new(k||(k=b("Promise")))(function(b){a.loadImmediately(function(a){delete q[r],n=e(a),b()})}));return c}function v(){var c=p[r];c||(c=p[r]=new(k||(k=b("Promise")))(function(b){a.onReady(function(a){n=e(a),delete p[r],b()})}));return c}function w(b){var f=b.ref;b=babelHelpers.objectWithoutPropertiesLoose(b,h);var g=b.loadImmediately;b=babelHelpers.objectWithoutPropertiesLoose(b,i);if(!n){var k=a.getModuleIfRequireable();k!=null&&(n=e(k));if(!n){!(l||(l=c("ExecutionEnvironment"))).isInBrowser&&!a.isAvailableInSSR_DO_NOT_USE()&&(m||(m=c("suspendOrThrowIfUsedInSSR")))("Loading bootloaded and T3 components are disabled during SSR");k=g===!0?u():v();(j||(j=d("PromiseAnnotate"))).setDisplayName(k,w.displayName);throw k}}return o.jsx(n,babelHelpers["extends"]({},b,{ref:f}))}w.displayName=w.name+" [from "+f.id+"]";g=a.getModuleId();a.isRequireDeferredForDisplay()===!0?g="requireDeferredForDisplay"+("("+a.getModuleId()+")"):a.isRequireDeferredForDisplay()===!1&&(g="requireDeferred"+("("+a.getModuleId()+")"));w.displayName="deferredLoadComponent("+g+")";g=w;s(a,g);return g}g["default"]=a}),98);
__d("deferredLoadComponent",["deferredLoadComponentBase"],(function(a,b,c,d,e,f,g){var h=function(a){return a};function a(a){return c("deferredLoadComponentBase")(a,h)}g["default"]=a}),98);
__d("requireDeferredForDisplay",["RDFDRequireDeferredReference"],(function(a,b,c,d,e,f,g){"use strict";function a(a){a=new(c("RDFDRequireDeferredReference"))(a);a.setRequireDeferredForDisplay(!0);return a}g["default"]=a}),98);/*FB_PKG_DELIM*/
__d("BanzaiWWW",["cr:1642797"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:1642797")}),98);
__d("CometClientRootRendererUtils",["ReactDOM","react"],(function(a,b,c,d,e,f,g){"use strict";var h;h||d("react");var i=!1;function a(){return i}function j(a,b){var c=document.getElementById(a);c||(c=document.createElement("div"),c.id=a,document.body.appendChild(c));b&&b.setupNavigationMutationRoot(c);return c}function b(a){var b=a.CometVisualCompletion,c=a.rootComponent,e=a.rootElementID;a=a.rootOptions;if(i)return;e=d("ReactDOM").createRoot(j(e,b),a);e.render(c);i=!0}g.getIsClientSideRendered=a;g.getOrCreateRootElement=j;g.initReactRender=b}),98);
__d("VultureJSGating",["justknobx"],(function(a,b,c,d,e,f,g){"use strict";var h=!1;function a(){h=!0}function b(){return h?!1:c("justknobx")._("2635")}function d(){return c("justknobx")._("3532")}g.__DO_NOT_USE_DISABLE_VULTURE_JS_LOGGING=a;g.isLoggingEnabled=b;g.isLowVolumeLoggingEnabled=d}),98);
__d("WAWebMediaEditorEnumsThemes",["$InternalEnum"],(function(a,b,c,d,e,f){"use strict";a=b("$InternalEnum").Mirrored(["ATTACH","CAPTURE","STATUS","POLL"]);f.MediaTheme=a}),66);
__d("WAWebStylexVars.stylex",[],(function(a,b,c,d,e,f,g){a={maxWidth:"var(--xhyx648)",__varGroupHash__:"xetn067"};b={maxWidth:"var(--x11s6emu)",__varGroupHash__:"xv58lhs"};c={groupProfilePictureWrapperPaddingStart:"var(--x1oim50r)",groupProfilePictureWrapperPaddingEnd:"var(--x53dyk0)",groupProfilePictureInsetInlineStart:"var(--xu8kjpt)",__varGroupHash__:"x1rdhdjq"};({docBlue:"#2E6AC5",pdfRed:"#D10335",pptOrange:"#CB5031",xlsGreen:"#218D51",docDarkBlue:"#BDD8F4",xlsDarkGreen:"#B8E4D0",pptDarkOrange:"#FFCBBB",genericDoc:"#CCE5F0",genericSpreadsheet:"#D2EEDF",genericPresentation:"#F5DCD6",pdfDarkRed:"#FFE6E6"});d={docBlue:"var(--x184htih)",pdfRed:"var(--xo8ean6)",pptOrange:"var(--xe71aag)",xlsGreen:"var(--xpfytx8)",docDarkBlue:"var(--xvwd1hk)",xlsDarkGreen:"var(--x1xm2y6c)",pptDarkOrange:"var(--xq94u1m)",genericDoc:"var(--x1i7f8yd)",genericSpreadsheet:"var(--x87lr8f)",genericPresentation:"var(--xbz2rmu)",pdfDarkRed:"var(--x1rq6j38)",__varGroupHash__:"x14fhudn"};e={height:"var(--x1b5hoai)",__varGroupHash__:"x1dhe5te"};f={layer0:"var(--x1w4oh5j)",layer1:"var(--x11mxrwm)",layer2:"var(--xm343uc)",layer3:"var(--x1y9a6jq)",layer4:"var(--x1lieqwx)",layer5:"var(--xeqnf2j)",layer6:"var(--x169ux90)",layer7:"var(--xpavtr9)",layer8:"var(--x19hyz7h)",layer9:"var(--x1r1wmrs)",layer10:"var(--xjyn5s5)",__varGroupHash__:"xe8divb"};g.conversationPanelVariables=a;g.rightPanelVariables=b;g.messageWrapperVariables=c;g.MsOfficeDocColors=d;g.reactionBubbleVariables=e;g.zLayers=f}),98);/*FB_PKG_DELIM*/
/**
 * License: https://www.facebook.com/legal/license/V9vdYColc4k/
 */
__d("react-0.0.0",["React"],(function(a,b,c,d,e,f){"use strict";function a(a){return a&&typeof a==="object"&&"default"in a?a["default"]:a}var g=a(b("React"));d={};var h={exports:d};function i(){h.exports=g}var j=!1;function k(){j||(j=!0,i());return h.exports}function c(a){switch(a){case void 0:return k()}}e.exports=c}),null);
__d("react",["react-0.0.0"],(function(a,b,c,d,e,f){e.exports=b("react-0.0.0")()}),null);